version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/knadh/koanf/v2.Koanf).Load
        - (*github.com/knadh/koanf/v2.Koanf).Set
        - (*github.com/knadh/koanf/v2.Koanf).MergeAt
        - (*github.com/knadh/koanf/v2.Koanf).Unmarshal
    revive:
      rules:
        - name: comment-spacings
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - goconst
          - gocyclo
          - gosec
        path: _(test|mocks)\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
