version: 2

builds:
  - id: quartz
    main: ./cmd/quartz/main.go
    binary: quartz
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.buildDate={{ .Timestamp }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats:
    - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats:
        - zip

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

binary_signs:
  - {}

signs:
  - artifacts: all
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
