# Codecov configuration for quartzctl
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        # Set target to be the same as base coverage, allowing minor decreases
        target: auto
        threshold: 2%  # Allow 2% decrease from base
        informational: false
    patch:
      default:
        # Reduce patch coverage requirement for integration-heavy code
        target: 50%
        threshold: 5%
        informational: false

# Ignore files that are difficult to unit test due to external dependencies
# These files primarily contain CLI integration code with exec.CommandContext
ignore:
  # AWS CLI integration code - uses exec.CommandContext extensively
  - "internal/cmd/aws_cleanup.go"
  # Main entry point
  - "cmd/quartz/main.go"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
