version: '3'

# waiting for a future release to enable taskfile defined
# env vars to override the shell environment
# TODO: remove all the inline CGO_ENABLED=0 statements when done
# https://github.com/go-task/task/issues/1038
# env:
#   CGO_ENABLED: '0'

vars:
  # https://github.com/go-task/task/issues/892#issuecomment-1278217185
  SHELL: '{{if eq .OS "Windows_NT"}}pwsh -c{{end}}'

tasks:
  build-all:
    cmds:
      - goreleaser build --clean --auto-snapshot

  build:
    cmds:
      - mkdir -p ./bin
      - goreleaser build --clean --snapshot --single-target --output ./bin/quartz
      - ./bin/quartz --version

  compress:
    deps: [build]
    cmds:
      - upx --best --lzma ./bin/quartz

  release:
    cmds:
      - goreleaser release --clean

  install:
    deps: [build]
    cmds:
      - '{{.SHELL}} cp ./bin/quartz* ~/go/bin'

  test:
    sources:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
    cmds:
      - CGO_ENABLED=0 go test -json -cover ./... {{ if .RUN }}-run {{ .RUN }}{{ end }} | tparse -all

  test-ci:
    cmds:
      - CGO_ENABLED=0 go test -json -cover ./...

  lint:
    cmds:
      - golangci-lint run -v

  tar:
    deps: [build-all]
    dir: dist
    cmds:
      - rm -f ../quartz.tar.gz || true
      - rm -rf pkg || true
      - for:
          matrix:
            OS: ["linux", "darwin"]
            ARCH: ["amd64", "arm64"]
        cmd: mkdir -p pkg/{{.ITEM.OS}}/{{.ITEM.ARCH}} && cp quartz_{{.ITEM.OS}}_{{.ITEM.ARCH}}_*/quartz* pkg/{{.ITEM.OS}}/{{.ITEM.ARCH}}/
      - cd pkg && tar -czvf ../../quartz.tar.gz *

  deps-update:
    cmds:
      - go get -u ./...
      - go mod tidy
