name: Build

on:
  workflow_dispatch: {}
  push:
    branches:
    - "main"
    tags:
    - "v*"
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.set_env.outputs.BUILD_VERSION }}
      build_date: ${{ steps.set_env.outputs.BUILD_DATE }}
    steps:
    - name: Set env
      id: set_env
      run: |
        echo "BUILD_VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        echo "BUILD_DATE=$(date '+%s')" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: setup

    permissions:
      id-token: write
      contents: write
      pull-requests: write
      actions: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.1
        cache: true

    - name: Run tests
      uses: gwatts/go-coverage-action@v2
      id: coverage
      with:
        coverage-threshold: 80
        fail-coverage: never
        cover-pkg: ./...
        ignore-pattern: |
          mocks\.go$
          ^main\.go$
        # this repo contains a lot of the source code for the app, keeping private for now
        report-url: https://github-quartz-cli.s3.amazonaws.com/go-coverage/${{ github.ref_name}}.html

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::204182206073:role/github-repo-quartz-cli
        aws-region: us-east-1

    - name: Upload coverage to s3
      if: always() && steps.coverage.outputs.report-pathname != ''
      run: |
        aws s3 cp ${{ steps.coverage.outputs.report-pathname }} s3://github-quartz-cli/go-coverage/${{ github.ref_name}}.html

    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: '-no-fail --exclude=G104 -nosec=true -fmt=html -out=gosec-report.html -stdout -verbose=text ./...'

    - name: Install Syft
      uses: anchore/sbom-action/download-syft@v0
      if: success() && startsWith(github.ref, 'refs/tags/')
      with:
        syft-version: v1.18.1

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v6
      if: success() && startsWith(github.ref, 'refs/tags/')
      with:
        install-only: true

    - name: Git status
      if: success() && startsWith(github.ref, 'refs/tags/')
      run: |
        git status

    - name: Release
      if: success() && startsWith(github.ref, 'refs/tags/')
      run: |
        BUILD_VERSION=${{ needs.setup.outputs.build_version }} BUILD_DATE=${{ needs.setup.outputs.build_date }} goreleaser release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
