name: lint

on:
  workflow_dispatch: {}
  push:
    branches:
    - "main"
  pull_request: {}

permissions:
  contents: read
  checks: write

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1
          cache: true

      - name: Run linter
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.5
